[Application.Connections.Dev]
host = "rabbitmq"
user = "agent-consumer"
pass = "lily0torque-mendez!since"
ssl = false

[Application.Consumers.workflow-runs]
consumer = "agent_consumer.consumer.AgentConsumer"
connections = ["Dev"]
qty = 1
queue = "workflow_runs"

[Logging]
version = 1

[Logging.formatters.console]
format = "%(asctime)s %(levelname)1.1s %(name)s: %(message)s"

[Logging.handlers.console]
class = "logging.StreamHandler"
formatter = "console"

[Logging.loggers.pika]
level = "DEBUG"
handlers = ["console"]

[Logging.loggers.rejected]
level = "DEBUG"
handlers = ["console"]
