[project]
name = "github-webhook"
version = "0.0.0"
description = "Receives GitHub webhook notifications"
requires-python = ">=3.14"
license = "BSD-3-Clause"
authors = [{ name = "Dave Shawley", email = "daveshawley@gmail.com" }]
dependencies = [
  "fastapi",
  "fastapi-runner",
  "fastapi-utilities",
  "pydantic",
  "pydantic-settings",
  "uvicorn[standard]",
  "uvloop",
]

[project.entry-points."fastapi_runner"]
configure = "github_webhook.entrypoint:configure"

[build-system]
requires = ["uv_build~=0.11.29"]
build-backend = "uv_build"
