[project]
name = "github-webhook"
version = "0.0.0"
description = "Receives GitHub webhook notifications"
requires-python = ">=3.14"
license = "BSD-3-Clause"
authors = [{ name = "Dave Shawley", email = "daveshawley@gmail.com" }]
dependencies = [
  "fastapi>=0.141.1",
  "httptools>=0.8.0",
  "pydantic~=2.13",
  "pydantic-settings>=2.15.0",
  "uvicorn>=0.52.4",
  "uvloop>=0.22.1",
]

[build-system]
requires = ["uv_build~=0.11.29"]
build-backend = "uv_build"
